In [1]:
from pandas import read_csv
from pathlib import Path

In [4]:
path = Path('good.csv')
data = read_csv(path)
data

,Time [s],CLK,A13,A14,A15,MODE0,MODE1,IOM,POWER,STATE0,STATE1,ROM0_CS,RAM0_CS,RAM1_CS,BSRE,ROM1_CS,RDY
0,-3.598561,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0
1,-0.011501,0,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0
2,-0.011494,0,0,1,1,1,1,1,0,0,0,0,0,0,0,0,0
3,-0.011487,0,0,0,1,1,1,1,0,0,0,0,0,0,0,0,0
4,-0.011480,0,0,0,0,1,1,1,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15272,52.038422,1,1,1,1,1,1,1,0,0,0,1,1,1,0,1,1
15273,52.038424,1,1,1,1,1,1,1,0,0,0,1,1,1,0,1,0
15274,52.038424,1,1,1,1,1,1,1,0,0,0,1,1,1,0,0,0
15275,52.038425,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0
15276,70.420665,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0

In [8]:
data['up'] = (data['POWER'].diff() == 1)
data[data['up']]['up']

7        True
14       True
21       True
27       True
34       True
41       True
47       True
54       True
57       True
60       True
63       True
3824     True
3830     True
3837     True
3844     True
3850     True
3857     True
3864     True
3869     True
3872     True
3875     True
3878     True
7636     True
7645     True
7651     True
7658     True
7664     True
7671     True
7677     True
7684     True
7688     True
7691     True
7694     True
7697     True
11462    True
11470    True
11476    True
11482    True
11488    True
11495    True
11501    True
11508    True
11511    True
11514    True
11517    True
Name: up, dtype: bool